server:
  port: 50001
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: consultants
      host: localhost
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
categories:
  service: CATEGORIES
  
teams:
  service: TEAMS
  
skills:
  service: SKILLS

sites:
  service: SITES
  
leaders:
  service: LEADERS

events:
  service: EVENTS
    
management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
      
amqp:
  teams:
    queue:
      consultant:
        added:
          request: consultant_added_team_consultants_response_queue
        updated:
          request: consultant_updated_team_consultants_response_queue
        removed:
          request: consultant_removed_team_consultants_response_queue
        finished:
          request: consultant_finished_team_consultants_response_queue
    exchange:
      consultant:
        added:
          team: teams_consultant_added
        updated:
          team: teams_consultant_updated
        removed:
          team: teams_consultant_removed
        finished:
          team: teams_consultant_finished
    key:
      consultant:
        added:
          request: consultant_added_team      
        updated:
          request: consultant_updated_team
        removed:
          request: consultant_removed_team  
        finished:
          request: consultant_finished_team
          
