server:
  port: 50015
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: projects
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

clients:
  service: CLIENTS

consultants:
  service: CONSULTANTS
  
teams:
  service: TEAMS
  
skills:
  service: SKILLS

sites:
  service: SITES  

amqp:
  projects:
    exchange:
      created:
        project: projects_created
      closed:
        project: close_project_exchange
    key:
      created:
        request: project_created
      closed:
        request: close_project_key
  
  teams:
    queue:
      created:
        request: team_created_projects_response_queue
      updated:
        request: team_updated_projects_response_queue
      consultant:
        added:
          request: consultant_added_team_projects_response_queue
        updated:
          request: consultant_updated_team_projects_response_queue
        removed:
          request: consultant_removed_team_projects_response_queue
        finished:
          request: consultant_finished_team_projects_response_queue
    exchange:
      created:
        team: teams_created
      updated:
        team: teams_updated
      consultant:
        added:
          team: teams_consultant_added
        updated:
          team: teams_consultant_updated
        removed:
          team: teams_consultant_removed
        finished:
          team: teams_consultant_finished
    key:
      created:
        request: team_created
      updated:
        request: team_updated
      consultant:
        added:
          request: consultant_added_team
        updated:
          request: consultant_updated_team
        removed:
          request: consultant_removed_team
        finished:
          request: consultant_finished_team
